name: Flutter tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      checks: write  #

    strategy:
      matrix:
        flutter-version:
          - "3.7.0"

    steps:
      - name: ğŸ“š Git Checkout
        uses: actions/checkout@v3.1.0

      - name: ğŸ¦ Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.flutter-version }}

      - name: Install LCOV
        run: sudo apt-get install -y lcov && dart pub global activate coverage

      - name: ğŸ“¦ Install Dependencies (root)
        run: flutter pub get

      - name: ğŸ§ª Run Tests
        run: flutter test --coverage

      - name: ğŸ“Š Collect coverage
        uses: codecov/codecov-action@81cd2dc8148241f03f5839d295e000b8f761e378
        with:
          files: coverage/lcov.info
          verbose: true